### ISSUE TITLE
Pushing to Production

### ISSUE THREAD

**Issue by alvogt** [SalesforceLabs/survey-force#100]
I can't uninstall Production and reinstall. So, I am trying to push from our Partial Sandbox to Production in pieces. I am encountering a bunch of Apex Test class errors. I'm just trying the push the two SFDC Apex files and test classes.  Can you help me with this error?

SFDCAccessControllerTest | testAccessControl | System.AssertException: Assertion Failed: Expected: false, Actual: trueStack Trace: Class.SFDCAccessControllerTest.testAccessControl: line 141, column 1
-- | -- | --

**Comment by jrattanpal** [comment]
It seems you have same issue as earlier user. You can find details at https://github.com/SalesforceLabs/survey-force/issues/94

In summary, you have enabled https://help.salesforce.com/articleView?id=000328426&type=1&mode=1 and that is causing the test to fail. 

You can temporarily disable that and install these classes. Or you can change that code to remove that test.

It's in https://github.com/SalesforceLabs/survey-force/blob/master/force-app/main/default/classes/SFDCAccessControllerTest.cls (line#141 and 142)

**Comment by jrattanpal** [comment]
Closing as per https://github.com/SalesforceLabs/survey-force/issues/101
