### ISSUE TITLE
Push to Production 2

### ISSUE THREAD

**Issue by alvogt** [SalesforceLabs/survey-force#101]
Thank you for the last fix that worked!

Now here is my next issues:

SurveyAndQuestionController_Test | testUpdateSurveyName | SFDCAccessControlException: Script-thrown exceptionStack Trace: Class.SFDCAccessController: line 283, column 1 Class.SFDCAccessController: line 78, column 1 Class.SurveyAndQuestionController.updateSurveyName: line 427, column 1 Class.SurveyAndQuestionController_Test.testUpdateSurveyName: line 125, column 1
-- | -- | --
SurveyAndQuestionController_Test | testsaveAndNewQuestion | System.AssertException: Assertion Failed: Expected: 5, Actual: 4Stack Trace: Class.SurveyAndQuestionController_Test.testsaveAndNewQuestion: line 51, column 1
SurveyAndQuestionController_Test | testsavesaveQuestion | System.AssertException: Assertion Failed: Expected: 5, Actual: 4Stack Trace: Class.SurveyAndQuestionController_Test.testsavesaveQuestion: line 76, column 1
SurveyAndQuestionController_Test | testupdateSurveyThankYouAndLink | SFDCAccessControlException: Script-thrown exceptionStack Trace: Class.SFDCAccessController: line 283, column 1 Class.SFDCAccessController: line 78, column 1 Class.SurveyAndQuestionController.updateSurveyThankYouAndLink: line 445, column 1 Class.SurveyAndQuestionController_Test.testupdateSurveyThankYouAndLink: line 138, column 1

ViewSurveyController_Test | testViewSurveyController_consutructor2 | System.QueryException: Insufficient permissions: secure query included inaccessible fieldStack Trace: Class.ViewSurveyController.<init>: line 89, column 1 Class.ViewSurveyController_Test.testViewSurveyController_consutructor2: line 85, column 1
-- | -- | --
ViewSurveyController_Test | testViewSurveyController_consutructor3 | System.QueryException: Insufficient permissions: secure query included inaccessible fieldStack Trace: Class.ViewSurveyController.<init>: line 89, column 1 Class.ViewSurveyController_Test.testViewSurveyController_consutructor3: line 26, column 1

**Comment by jrattanpal** [comment]
I can't say without looking at actual errors in Apex log. 

But it seems like permission issue? Anything that is in SFDCAccessControlException seems to be permission issue.

**Comment by alvogt** [comment]
How do I get the actual log for the Apex?

**Comment by jrattanpal** [comment]
This is interesting. I haven't seen this error before. It seems like you maybe missing some fields in your change set when you try to promote those changes to your production org. 

For example, one of the error message is in https://github.com/SalesforceLabs/survey-force/blob/master/force-app/main/default/classes/SurveyAndQuestionController.cls at line 445. 

It is               sqToUpdate.OrderNumber__c = i;


Now why will it fail when trying to acces that field? Unless it's missing?


As for Apex log, I now understand you are trying to deploy changeset. I am not sure if we can get Apex logs there.

**Comment by jrattanpal** [comment]
I will close this issue for now as it seems it has been resolve. If not then feel free to reopen or create new issue
