### ISSUE TITLE
Survey Force (v2.21) Permission sets aren't available for guest user.

### ISSUE THREAD

**Issue by ahmedsadiqcs** [SalesforceLabs/survey-force#102]
Hi Team,

We are using the "Survey force" package (v 2.21) in our "Enterprise Edition" org.

The problem is Salesforce is not longer providing edit access to site guest users, due to which surveys are not reaching out to salesforce. In order to resolve this issue, we need to give edit the access using permission sets.

Survey force (v 2.21) doesn't have these latest permission sets but the latest version does have these permission sets.

```
- Survey_Force_Admin.permissionset
- Survey_Force_Guest.permissionset
- Survey_Force_SuperAdmin.permissionset
```

In order to get the latest version, I need to reinstall the packages, as the package is un-managed.
This may cause deletion of survey data which is very important to us also many automations are attached to custom survey objects.

Please provide me your expert opinion on what should I do to make it working,
Any way to reinstall the package without losing any data or any way to inject the latest permission sets to the Survey force (v 2.21)

I'm looking forward to getting a resolution,
Thanks

**Comment by jrattanpal** [comment]
I have listed possible routes (there may be more) in the guide at https://github.com/SalesforceLabs/survey-force

Yes, you definitely need latest version. There have been many changes since 2.21; including fixes for Guest user issue.

**Comment by jrattanpal** [comment]
Closing this issue. You can create a new issue if needed.
