### ISSUE TITLE
Authorization Required (In both latest and older version)

### ISSUE THREAD

**Issue by jaegchoi** [SalesforceLabs/survey-force#103]
Hi, our organization is using an older Survey Force version (2.27) and because of the recent Guest User restrictions, surveys are broken for us now. 
To test that the latest version of Survey Force will work if we upgrade it I have checked out this repo and created a scratch org using the included sfdx-project.json. However, after following all steps I am still getting the Authorization Required error, but also a Script-thrown exception. I will list the steps I have followed below: 

Set the permissions on the guest user profile of the site 
![image](https://user-images.githubusercontent.com/22580247/110680593-cedbd600-81a6-11eb-9963-2e744f5dcd71.png)

TakeSurvey page is added to the enabled pages list on the site
![image](https://user-images.githubusercontent.com/22580247/110681256-a1dbf300-81a7-11eb-90e0-8888ac2c00aa.png)

Survey sharing rule has been added
![image](https://user-images.githubusercontent.com/22580247/110681304-b15b3c00-81a7-11eb-856f-3cff7bf0023b.png)

I am able to preview the TakeSurvey page but if I try to view or preview the URL for the survey I get this unauthorized page 
![image](https://user-images.githubusercontent.com/22580247/110682226-b2d93400-81a8-11eb-87fb-1122ebff86a2.png)
![image](https://user-images.githubusercontent.com/22580247/110681592-fe3f1280-81a7-11eb-93e0-9278594b246e.png)

Please let me know if I missed any steps or if there is anything else I can try, as this is affecting our prod environment

**Comment by jrattanpal** [comment]
It all looks good. Only thing I can think of is, have you also given access to ALL fields in those objects? While you can give read access to those objects, you must also give access to each field. 

If you have then please capture debug logs for this page and share here (attach as a file) so I can take a look.


https://www.forcetalks.com/salesforce-topic/how-to-set-the-debug-for-guest-user-in-salesforce/

**Comment by jrattanpal** [comment]
Closing this issue for now. Once you have the logs, you can reopen
