### ISSUE TITLE
Should public surveys show the guest user as the Survey Taker?

### ISSUE THREAD

**Issue by dschach** [SalesforceLabs/survey-force#110]
We can populate the Sites guest user in the User field on Survey Taker object. This would let an org know which site the Survey was taken in. 
Alternatively, we can populate a different field with the Site (using "Internal" for internal surveys.
What do people think?

**Comment by jrattanpal** [comment]
We can't make Guest user owner of a record as per new security setting. We can create a custom checkbox field (maybe "Completed by Guest User").

**Comment by jrattanpal** [comment]
@dschach 

I see you implemented it already. Thanks again!!


(Closing this issue for now)
