### ISSUE TITLE
survey force was working - now not working for external survey

### ISSUE THREAD

**Issue by garysecor** [SalesforceLabs/survey-force#113]
noticed there was a new version as of -415 - did that somehow make 254 version stop working ?  Any thoughts appreciated - it appears we will loose surveys we have created when we uninstall the 254 version and install the new 256 version - seems like a waste!
help

**Comment by jrattanpal** [comment]
The version in your org should continue to work. New updates will not cause any changes in your org.

@dschach has helped clean up some code and add few more features. We do recommend you look into new changes but it's not required. Although, the upgrade process is not easy because Survey Force is un-managed package. We have suggested some options in documentation (towards the end of the page) at https://github.com/SalesforceLabs/survey-force

**Comment by jrattanpal** [comment]
What is the error that you are getting?

**Comment by garysecor** [comment]
No error—survey just not appearing unless you are logged in even for external survey – was working a few days ago ok.

 

Thanks

Gary

 

Gary Secor

Vice President CIO

Cloudtroupe

Direct     678-478-6776 

 ***@***.***> ***@***.*** 

 <http://www.cloudtroupe.com> www.cloudtroupe.com

**Comment by jrattanpal** [comment]
https://c.na109.visual.force.com/apex/takesurvey?id=a1P3f000001ETczEAG&cId=none&caId=none  is an INTERNAL page (visual.force.com).

There should be a different URL for your site that you setup (Setup->Sites). You should be using that URL.

You can get that URL by Going to Survey detail page and using that "Share" component on the first tab of that details page.

**Comment by garysecor** [comment]
<https://gumf.secure.force.com/TakeSurvey?id=a1P3f000001ETczEAG&cId=none&caId=none> https://gumf.secure.force.com/TakeSurvey?id=a1P3f000001ETczEAG&cId=none&caId=none

  

ok – now getting authorization required message

 



 

Gary Secor

Vice President CIO

Cloudtroupe

Direct     678-478-6776 

 ***@***.***> ***@***.*** 

 <http://www.cloudtroupe.com> www.cloudtroupe.com

**Comment by jrattanpal** [comment]
Right, now you need to capture Apex debug logs so I can check what maybe wrong. As far as I know, it's a FLS/CRUD issue somewhere. I don't know why it suddenly stopped but someone may have changed something.

- Check that Site Guest user has appropriate permissions to SUrvey objects as mentioned in https://github.com/SalesforceLabs/survey-force
- Check that a Sharing rule is created to allow access to Surveys to guest user.
- Make sure TakeSurvey VF page is added to Visualforce page list


In general, go through all the steps in https://github.com/SalesforceLabs/survey-forcehttps://github.com/SalesforceLabs/survey-force to make sure all is configured properly

**Comment by dschach** [comment]
The most common reason to get the authorization required message on a public survey is that you haven't assigned the guest user permission set to the site user. Instructions are on the readme in this repository.

**Comment by garysecor** [comment]
Thanks – I went back over the settings – we are good now – thanks sincerely for your attention and emails.

 

Gary

 

Gary Secor

Vice President CIO

Cloudtroupe

Direct     678-478-6776 

 ***@***.***> ***@***.*** 

 <http://www.cloudtroupe.com> www.cloudtroupe.com

**Comment by jrattanpal** [comment]
Glad to hear this issue has been resolved. I will close this. Feel free to log a new issue if you encounter any other error
