### ISSUE TITLE
SurveyManagerController_Test errors on unrelated Change Set Deployment

### ISSUE THREAD

**Issue by Molly-Chicago** [SalesforceLabs/survey-force#115]
We haven't touched the survey objects in a while.  We are now getting this error when trying to deploy a pretty simple change set:
_**System.QueryException: List has no rows for assignment to SObject
Stack Trace: Class.SurveyManagerController_Test.doTest_runAs2: line 15, column 1**_

Tried to download a fresh package from AppExchange and it says it cannot be upgraded in place.  Any idea what this is?  Are there incompatibilities with some of the platform changes to Apex?  Any workarounds without installing objects we have already customized?

**Comment by jrattanpal** [comment]
@Molly-Chicago 

Did someone update the test classes? This test class uses a permission set called "Survey Force - Guest". We added that a while back. If someone on your site didn't update that Apex code then maybe someone accidentally deleted that Permission set?

As for upgrading to latest version, unfortunately Survey Force is un-managed package. That means it cannot be upgraded. We have listed couple of options for upgrading to latest version at https://github.com/SalesforceLabs/survey-force (towards the end of documentation)

**Comment by Molly-Chicago** [comment]
Yes - it does appear that the Survey Force Guest permission set is gone.  I've just created one with that name that has access to the survey objects.  I'll poke around to see if I can find the details on how it should be configured on the site.    Thanks!
