### ISSUE TITLE
how to add question

### ISSUE THREAD

**Issue by cucojoel** [SalesforceLabs/survey-force#116]
hi
i cant create any question, de button is disabe, i try in classic version and ligthning, the package was install today 30-apr-2021,
**the user admin have all permision set
![image](https://user-images.githubusercontent.com/11685169/116739673-90e67b80-a9b9-11eb-868e-b4326d5a0b06.png)

**Comment by dschach** [comment]
Thank you. We're working on a fix. 
In the meantime, on SurveyPage (the Visualforce page) on line 157, delete 
`disabled="{!theQuestion.Type__c == ''}"`
and you'll be fine. The error messages may not show if you try to save a question without specifying a type, but you'll be able to save ones with a type.

**Comment by cucojoel** [comment]
thanks, the button is available now, when I try to save, display a message with the following caption...
argument cannot be null.

**Comment by jrattanpal** [comment]
@dschach 

Do you know which code may be causing that second error?

**Comment by dschach** [comment]
Am starting new fork to troubleshoot now

**Comment by dschach** [comment]
Pull request submitted

**Comment by cucojoel** [comment]
i have not sure, i try add any question, but not success, try mod the code to catch the moment or error
