### ISSUE TITLE
Survey Taker not triggering Flow by Created, only edited

### ISSUE THREAD

**Issue by dsurico** [SalesforceLabs/survey-force#125]

**Comment by jrattanpal** [comment]
Can you add more details? 

But as you edited it, I am guessing it now works?

**Comment by dsurico** [comment]
Hi! It does work now, thank you!

I do have another question that I need your help with:  How do I add the Contact Owner to the Survey Taker object and/or list?

Essentially, I need to create a Survey Taker with Responses Report that includes the Contact's  Owner (First name) in the report so that my team members can see which of their contacts completed the survey and can respond to them accordingly.

I tried adding a look up field on the Survey Response object, but that didn't work.



If you have any suggestions - I would be very grateful!

Thanks

Dee

_



primacy



***@***.******@***.***>

marketing solutions specialist

561.379.9964



theprimacy.com<https://www.theprimacy.com/>



Primacy is a data-inspired, full-service digital experience agency. We create smarter experiences that connect with people during meaningful moments.


________________________________

**Comment by jrattanpal** [comment]
For that, you should be able to use Contact record lookup to owner.

Survey_Taker__c.Contact__c.Owner.Name (not sure the correct reference)

You should be able to get that in report. If you want it to on Survey Taker then create a formula field to show it there and use that in report

**Comment by dsurico** [comment]
Thank you! I will try this now!
