### ISSUE TITLE
Error: Data Not Available

### ISSUE THREAD

**Issue by bwwestbrook** [SalesforceLabs/survey-force#126]
I installed Survey Force Version 2.59 on 6/15/2021

I'm attempting to make the surveys public, but am getting an "Error: Data Not Available"

I've checked all the settings and "think" I have them all set, but obviously I'm missing something.

I'm attaching photos and a debug log.  Thanks for your help.

![image](https://user-images.githubusercontent.com/52218853/128199030-fbb769ba-f461-4fb5-91b7-62ae0f1172c7.png)

![image](https://user-images.githubusercontent.com/52218853/128199266-b2201537-0aca-4dfc-8f4f-29b66a9d462a.png)

![image](https://user-images.githubusercontent.com/52218853/128199393-96842d1c-3671-4696-a1e5-fd9cfa8c349b.png)

![image](https://user-images.githubusercontent.com/52218853/128199517-7f14d6c7-bbe7-423f-a7ed-d4ad98d84dd9.png)

![image](https://user-images.githubusercontent.com/52218853/128199668-f4a53eeb-7eaa-4b25-99bd-a40df984ac93.png)

![image](https://user-images.githubusercontent.com/52218853/128199889-eefc7609-7ed3-470d-9b21-5c3fd4f35710.png)

[apex-07L0y0000587qHyEAI.log](https://github.com/SalesforceLabs/survey-force/files/6932017/apex-07L0y0000587qHyEAI.log)

[apex-07L0y0000587qI3EAI.log](https://github.com/SalesforceLabs/survey-force/files/6932018/apex-07L0y0000587qI3EAI.log)

**Comment by jrattanpal** [comment]
Logs don't have any information so it's hard to say what is going on. Maybe there was another log file that you didn't attach?

You just need to make sure that you go through **ALL** configuration steps mentioned at https://github.com/SalesforceLabs/survey-force

**Comment by bwwestbrook** [comment]
Thank you so much for your assistance.  I started from scratch with a brand new SITE and was able to get it to work.

**Comment by jrattanpal** [comment]
Glad that worked out!

I will closet his issue for now. Feel free to open a new one if needed.
