### ISSUE TITLE
Translate surveys + error message

### ISSUE THREAD

**Issue by Tanguybolt** [SalesforceLabs/survey-force#130]
Hi there, 

I've managed to send surveys to external users, but I still experience 2 issues:

1) I want to translate the survey, but Translate settings from Salesforce are only applicable for the standard object. Since this is a custom object, I do not get the option. Is there a workaround or something I'm overlooking?

2) I get the error message "List has no rows for assignment to SObject". I already shared the report folder with the correct user, but this did not resolve the issue. Am I overlooking something? (see screenshot)
![Screenshot 2021-12-07 at 16 56 32](https://user-images.githubusercontent.com/95703785/145062565-d9f7ee04-e682-46a6-8429-cd3c40d26699.png)

Thanks in advance!

**Comment by jrattanpal** [comment]
1. You should see this option for custom objects in Translation workbench
2. For the error, can you upload Apex debug log? That should tell us what maybe happening here.
