### ISSUE TITLE
Email trigger from Production org showing "Authorization Required " error where from Sandbox works fine

### ISSUE THREAD

**Issue by souravp2k5** [SalesforceLabs/survey-force#133]
Hi,
I created the survey template, But while triggering the email from Prod org its showing the "Authorization Required " error while clicking the link, while working OK from Sandbox Org. Please suggest what can be the issue ?
I tried the debug log but its all success as the emails is delivered.

![12](https://user-images.githubusercontent.com/22519635/147919452-47a481e2-9723-4b61-83b1-8262ffa9ee56.JPG)

**Comment by jrattanpal** [comment]
Can you capture and share your apex debug logs?

There is some missing confirmation or permission. You need to make sure that you have gone through ALL steps mentioned at https://github.com/SalesforceLabs/survey-force

**Comment by souravp2k5** [comment]
Thanks @jrattanpal , I went through all the permissions mentioned and it seems some were missing. After assigned those work perfectly.

**Comment by jrattanpal** [comment]
Great to hear @souravp2k5 !

I'll close this issue. Feel free to log another issue if you have any further questions.
