### ISSUE TITLE
Survey Header Text is not displaying in Survey page

### ISSUE THREAD

**Issue by sherineraj** [SalesforceLabs/survey-force#136]
I setup public access setting and gave Read only permissions to Survey__c object , but I don't see survey header content. Please suggest a solution to resolve this issue.

**Comment by jrattanpal** [comment]
@sherineraj 

I have seen this in the past. THis is the result of some missing permissions. Please go through ALL the steps mentioned at https://github.com/SalesforceLabs/survey-force and ensure that all permissions are assigned to guest user.

**Comment by sherineraj** [comment]
@jrattanpal How do I control the response to guest user? How to set the Emailable link as constant? I always need to choose the sharing option and select site from "Share My Survey" to get emailable link.

**Comment by jrattanpal** [comment]
That is controlled in apex in https://github.com/SalesforceLabs/survey-force/blob/main/force-app/main/default/classes/ViewShareSurveyComponentController.cls

If you set "surveyId" and "selectedURLType", then you can call surveyURLBase() and surveyURL() to get that link. 

You will need to use Apex for that

**Comment by sherineraj** [comment]
Resolved
