### ISSUE TITLE
Person Account  Survey Force - IFrameOrigin Null

### ISSUE THREAD

**Issue by LuciaMCSF** [SalesforceLabs/survey-force#137]
Hi, I have created a survey, published it on a site, having used as sharing option the "Email Link w/Contact Merge".

I'm using the link in Marketing cloud retrieving the ContactID through Ampscript. The email and the link are correct and answers are sent back to Salesforce (I can see them in the survey reports).

Unfortunately answers are  not linked to the contacts.
Consider **we are using Person Account**.

This is an example of the link from Marketing Cloud to the VF page in SF:

**https://companyname.secure.force.com/TakeSurvey?id=a0d7U00000XXXXXX&cId=0037XXXXXXXX%7D&caId=none**

And this is the url when I submit the form:

**https://companyname.secure.force.com/TakeSurvey?id=a0d7U000000xxxxx&sfdcIFrameOrigin=null**

I suppose the issue comes from the Person Account and I wonder if you can give some instructions in order to solve this problem. I can't find any documentation on this.
Thanks so much

**Comment by jrattanpal** [comment]
Where do you get the Contact ID from Person Account?  Did you create a new contact from the Person account? or is it the behind-the-scenes Contact ID for the person account?

I haven't tested this scenario but I think you may need to use an account ID. In that case, you will need to change the code to add that feature as the current functionality is only for contact and case.

**Comment by LuciaMCSF** [comment]
Thank you @jrattanpal 
May I ask how can I check on Survey force why the end URL is missing the contactId? Because instead of the ContactId I see this [sfdcIFrameOrigin=null] and I don't understand if this is something that I have to investigate outside Survey Force. Thanks again

**Comment by jrattanpal** [comment]
Yes, this is outside of survey force. 

You mentioned that you send following URL from marketing
https://companyname.secure.force.com/TakeSurvey?id=a0d7U00000XXXXXX&cId=0037XXXXXXXX%7D&caId=none

But the submission URL (where user fills the form) is 
https://companyname.secure.force.com/TakeSurvey?id=a0d7U000000xxxxx&sfdcIFrameOrigin=null


Somewhere along the line, it looses "cid" and "said". You will need to figure out why those are missing and at what point.

You can confirm that this is not survey force issue by 
- Create a dummy Person Account for yourself
- generate link
- Use that link (without marketing cloud)

Check if Contact ID is saved (it did for me)

If that works (And it should) then that confirms surveyforce is working without issues

**Comment by LuciaMCSF** [comment]
Thanks @jrattanpal

**Comment by LuciaMCSF** [comment]
[](url
![Schermata 2022-02-23 alle 07 54 18](https://user-images.githubusercontent.com/65703614/155273438-25136d86-e0c2-4149-aa82-5e2331ff7645.png)
)

**Comment by LuciaMCSF** [comment]
@jrattanpal  I have tested as per your suggestion and this is what I see (previous comment) using the dummy test and the link outside Marketing Cloud. Could be something related to permissions? Thanks again

**Comment by jrattanpal** [comment]
URL in that screenshot is wrong. it should be in the following format

https://companyname.secure.force.com/TakeSurvey?id=a0d7U00000XXXXXX&cId=0037XXXXXXXX%7D&caId=none

**Comment by LuciaMCSF** [comment]
Thanks, @jrattanpal - upon further verification, the survey responses are linked to the correct person account, however, when the customers submit the answers, the error provided above persists. I think it might be related to some permissions - but I haven't figured out which permissions. Additionally, it might have something to do with the redirect of the page. Have you encountered this issue before? Thank you in advance for your help!

**Comment by jrattanpal** [comment]
@LuciaMCSF 

This shouldn't happen. On submit, they should see a thanks message. I am not sure why you are seeing that but I haven't seen this issue before. 

You can try attaching the apex debug log and I'll see if I can figure out what may be happening

**Comment by LuciaMCSF** [comment]
@jrattanpal  In the debug log I don't see any error. As you can see from the attached screenshot of the debug logs. All seem to be correct (Operazione riusciuta= Successful activity) but I see some operations are indicated as "/apex/unauthorized". 
I hope this helps
![apex_SurveyForce](https://user-images.githubusercontent.com/65703614/156132512-9a0321ee-69f9-4260-8e16-078c563c0968.png)

**Comment by LuciaMCSF** [comment]
here the file related to the operation linked to unauthorized
[apex-07L7U000000oZFCUA2.log](https://github.com/SalesforceLabs/survey-force/files/8160000/apex-07L7U000000oZFCUA2.log)

**Comment by jrattanpal** [comment]
It's log file after Unauthroized that you need to share. "TakeSurvey" one.

**Comment by LuciaMCSF** [comment]
@jrattanpal  here it is, thanks again
[apex-07L7U000000oZFBUA2.log](https://github.com/SalesforceLabs/survey-force/files/8163140/apex-07L7U000000oZFBUA2.log)

**Comment by jrattanpal** [comment]
Are you using the setting no survey where you redirect users to another URL when it's completed? Rather than thank you page?

It seems you have set it to "www.leonori.it". 

if you want that then I think you need to change that to "http://www.leonori.it" (or https://; whatever is correct)

If not then you need to remove that. It will be in one of the tabs when you edit survey

**Comment by LuciaMCSF** [comment]
@jrattanpal  putting the http in front of the website name I solved this issue. Thank you for your kindness and help!

**Comment by LuciaMCSF** [comment]
I can close the issue as it has been solved.
