### ISSUE TITLE
Clients are not able to submit survey results

### ISSUE THREAD

**Issue by TienFiti** [SalesforceLabs/survey-force#144]
Hi,

We noticed that some survey results were not submitted properly.

There are Survey Taker records without any related Survey Question Response record.
<img width="914" alt="image" src="https://user-images.githubusercontent.com/106715665/174941990-ea629c28-ee1b-4e74-a8bb-89cf921bf234.png">
We assume that the client submitted the survey so that there is the Survey Taker record, we don't have idea why there is no any response for the questions.
The survey contents some required questions, so there is no way to submit an empty survey result.

This issue was happened when we deployed and went live the Survey Force; it seems no such issue anymore but oddly enough that we didn't take any action to fix it. However the users still want to understand the root cause so that they can avoid bad customer experience.
Please advise, thanks a lot.

Tien

**Comment by jrattanpal** [comment]
Hi,

We do not have any logging mechanism to track past errors. You can capture debug logs to see what the issue maybe for new issues. BUt the old ones cannot be tracked.
