### ISSUE TITLE
Logo is not displaying in the survey header either internally nor externally

### ISSUE THREAD

**Issue by srikanthgoti** [SalesforceLabs/survey-force#145]
Hi, I've added the logo(Jpg format) through static resource in the survey header. but logo was not displaying. I've enabled all the permissions and Field level security on Survey Header field. Assigned super admin permission set to my user. still unable to view the logo

I've installed latest version and please find the attached screen shots

![survey](https://user-images.githubusercontent.com/108455972/176626991-860ec2dd-994b-4339-b704-0b4f5fa6a920.JPG)

![Header Logo](https://user-images.githubusercontent.com/108455972/176626995-bcb36a46-3eee-441c-911e-fc47eba210b3.JPG)

Appreciate your help !!

**Comment by jrattanpal** [comment]
You need to make sure that "Hide Survey name is unchecked. This field hides the survey name and header image

**Comment by srikanthgoti** [comment]
Thanks @jrattanpal . Now logo works. However i'm not able to remove Thank you (Which is in Big letters) message after submitted. Please see attached screen shot.
![Thank you](https://user-images.githubusercontent.com/108455972/176764130-be8b104f-4ddc-4ed7-b5de-15c46b1cf3db.JPG)

**Comment by jrattanpal** [comment]
That part is coded in https://github.com/SalesforceLabs/survey-force/blob/main/force-app/main/default/pages/TakeSurvey.page (line# 103-105) (the <header> portion)

You will need to update the code to remove that thank you. We haven't made that part conditional
