### ISSUE TITLE
Report Question

### ISSUE THREAD

**Issue by ekowkaay** [SalesforceLabs/survey-force#146]
I was wondering if there is a way to dynamically filter reports in the analytics report chart. The chart works great but we would like to view the report passed in the report chart.

**Comment by jrattanpal** [comment]
You can create more dashboards as you need. All this data is in your org and you can present it based on your needs. The chart that we accompanied with the app is very basic one and doesn't have many features

**Comment by ekowkaay** [comment]
okay, thanks!
