### ISSUE TITLE
Apostrophes in Questions?

### ISSUE THREAD

**Issue by Heather-Hanson** [SalesforceLabs/survey-force#161]
I was given a survey to create which has a lot of "Don't"s in the question and responses. Is there an escape character I can use to avoid it coming out like this: don\\\\\\\\\\\\\\\'t

**Comment by jrattanpal** [comment]
I have made changes in the code to fix this issue. 

You will need to use code from the following 2 files. If you are using original code and haven't made any custom changes then you can copy/paste code as-is.
PLEASE MAKE SURE TO TEST In sandbox BEFORE moving to production

- https://github.com/SalesforceLabs/survey-force/blob/main/force-app/main/default/triggers/SFSurveyQuestionTrigger.trigger
- - https://github.com/SalesforceLabs/survey-force/blob/main/force-app/main/default/classes/SurveyAndQuestionController.cls

You can see the changes I made at https://github.com/SalesforceLabs/survey-force/commit/cf0a51cff18c94ed08b54070a8a3b2d3fc0c088d
