### ISSUE TITLE
Conditional Branching

### ISSUE THREAD

**Issue by shatananda** [SalesforceLabs/survey-force#30]
Are there any plans for conditional branching support?

e.g. https://www.surveymonkey.com/mp/tour/skiplogic/

**Comment by jrattanpal** [comment]
Hi,

There are no plans to add this feature yet. But I might add this later. Although, if you want to add it then please feel free to commit to this repo and I can add it to package (it'd be great help).

Thanks

**Comment by jrattanpal** [comment]
Hi,

I am closing this issue as resolved for now. But let me know if yo u are interested in helping out to building this feature.

Thanks

**Comment by claico** [comment]
When Ron Hess was working on this, long time ago, he had a version which had conditional branching. The process was pretty complicated because you need the ability to back out responses that were on one branch if/user decides to go back and then down a second branch.

**Comment by jrattanpal** [comment]
This is currently not on the roadmap.

**Comment by shatananda** [comment]
ATTENTION: I will not be using the email shatananda@usa.net anymore.
      
      
        
      
      Please resend your email to nshatananda@gmail.com.
      
      
        
      
      Thanks very much,
      
      Noel
