### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by wahoobie** [SalesforceLabs/survey-force#33]
I'd like to get this setup for the first time in a dev instance but the following is resulting at install time:
This app can't be installed.
There are problems that prevent this package from being installed.
Illegal assignment from List<Profile> to profile
ViewSurveyController: Illegal assignment from List<Profile> to profile
Apex class 'ViewSurveyController' does not exist

The instance is Summer '17.  Any ideas?  Thank you!

**Comment by jrattanpal** [comment]
I believe this issue was fixed and it was because of object name issue
