### ISSUE TITLE
CSS code

### ISSUE THREAD

**Issue by elmord73** [SalesforceLabs/survey-force#37]
Hi!

I'm trying to add CSS code that will make all the questions and answers RTL.
I added to the css container:
**#survey_container{margin: 10px; direction: rtl}**

The questions are now RTL but the answers stll LTR (i;m using single-select vertical questions)

I tried several more options but nothing helped.
I was hoping you can help me solve this or at least tell me when I can find all the css options to add here.

Thanks!

**Comment by claico** [comment]
I did not have an answer for this initially, but I was reviewing apex tags available in Visualforce. 

The apex component [<apex:outputPanel>](https://developer.salesforce.com/docs/atlas.en-us.pages.meta/pages/pages_compref_outputPanel.htm) has a parameter "dir" which can be either RTL or LTR. 

You might try encasing your questions and possible responses in an <apex:outputPanel>
