### ISSUE TITLE
Unable to find Survey force installation guide

### ISSUE THREAD

**Issue by tsnathan** [SalesforceLabs/survey-force#38]
Hi

The link from the installation has only user guide and I am unable to find the installation guide. Not sure what I am missing.

Can you please share the installation guide link?

Thanks
Senthil

**Comment by jrattanpal** [comment]
I have added the instructions to https://github.com/SalesforceLabs/survey-force/blob/master/readme.md. (and updated the link)

Thanks for reporting!
