### ISSUE TITLE
I’m unable to attach a contact and case to the survey  

### ISSUE THREAD

**Issue by tthompson899** [SalesforceLabs/survey-force#39]
I’m able to create a survey within Salesforce however I’m not able to link it to a Contact or Case. I’m using the email link to paste to the Post chat Url under chat buttons for live chat - Is that even the correct way or am I missing something?

**Comment by jrattanpal** [comment]
Hi,

Sorry for the delay, I was making changes to the package. I tested it and it worked for me. I am not sure why it's not working for you but hard to say without being able to debug it.

I have just uploaded latest version of this where I fixed a few things. You should check that out and see if that may fix this issue.

**Comment by charles-thompson-salesforce-com** [comment]
@tthompson899 - Hi.  I think you may have to read through the user guide again.  

The feature to include references to case & contact records is in the URL that's generated when you create or update a survey.  

You can see these references embedded in the URL as "&cId={!Contact.Id}&caId={!Case.id}"  when you select the Sharing Option "Email link w/ Contact & Case Merge".  

This URL is designed to be embedded in an email invitation, which is how my customer uses it, but it could also be included in your post chat Visualforce page, as you have done.

My customer also does a survey at the end of eligible chats (those that are closed by the visitor), but uses custom code in the post chat Visualforce page which displays two questions (one for CSAT and one for NPS), each with only a thumbs up or down choice.  The Apex controller then saves the result in custom fields on the case.  It's a very hard-coded solution but gives the best customer experience, in my view.

**Comment by tthompson899** [comment]
I found a way to handle this via Apex
