### ISSUE TITLE
Is the App Multilingual?

### ISSUE THREAD

**Issue by manvijain21** [SalesforceLabs/survey-force#41]
We have multiple countries in the same Org. So please from US and Brazil for example are looking to use this. Can the App allow creating Surveys in different languages?

**Comment by wahoobie** [comment]
THere is no current out of the box solution. I was looking to create
additional field for label/question support while the core fields are in
English I could use a URL parameter and some controller/vf code to see they
are visiting the Spanish link so hide the English fields and render the
Spanish. There's a few things to consider like in my case I want to support
reporting in English but picklist are challenging and who knows what else.
I have yet to need support for this but we are investigating also. Perhaps
there is a better on-the-fly scenario but with specific field values we
curate we do not have to worry about bad translations.

**Comment by charles-thompson-salesforce-com** [comment]
My customer uses SurveyForce to support customers using 10 languages.  How do they do it?

1. One full survey per language -- each survey name includes the language code (e.g. en, th, my, etc)

2. One survey invitation email template per language -- also including the language code in the email template name. The template includes the link to the appropriate language survey.

3. Responses are scored (e.g. a positive response, regardless of which language, is given a 1 and a negative response gets a 0) using a custom formula field on the response.  This allows reporting on the percent of positive responses (so they can measure CSAT% per agent per month).

This works well and allows fairly easy maintenance.

We also have one survey that uses custom labels in the email template, allowing a single template with translations handled by Translation Workbench.  This also works well, but the survey itself is only presented in English.
