### ISSUE TITLE
Error occured when renaming Free Text question type.

### ISSUE THREAD

**Issue by eliver** [SalesforceLabs/survey-force#44]
Error <Argument cannot be null.> pops up when trying to editting a Free Text Question.

I have detected the issue is related to the following code in SurveyAndQuestionController --

`questionToUpdate.Choices__c = String.escapeSingleQuotes(qChoices);`

As the Choices__c for Free Text Question Type is always null, the funcation String.escapeSingleQuotes() will pop up an error if parm is null.

![image](https://user-images.githubusercontent.com/9433335/69218779-62515800-0bac-11ea-9792-4600995d57e2.png)

**Comment by jrattanpal** [comment]
Thanks for reporting this! Another thanks for providing the error line  that resulted in quick fix.

Fix for this has been submitted. https://github.com/SalesforceLabs/survey-force/commit/f7ca449b30f3ab0368a117cf062217097ca90d20

Please test it and let me know if you see any issues.
