### ISSUE TITLE
Survey opens at bottom of survey, user needs to scroll up to start survey

### ISSUE THREAD

**Issue by friscoandy** [SalesforceLabs/survey-force#49]
Hi. For some reason, when I open a survey, I have to scroll up to the top of the page to get to question 1. It is defaulting to the bottom of the page. We have tested this in Chrome and Firefox.

**Comment by jrattanpal** [comment]
I am not sure on this one. I can't reproduce it so hard to say what is going on. Maybe you have an extension causing this? Hard to say without looking/debugging javascript on the browser.

**Comment by friscoandy** [comment]
It is happening to multiple users on different browsers. I disabled my one extension but it still happens. If I provide you with a login to our sandbox, would you mind looking at it?

**Comment by jrattanpal** [comment]
Sorry, I am not allowed to take username/password this way.

**Comment by jrattanpal** [comment]
Hi,

I checked and I can help you with this. Please let me know how I can access that org and reproduce. 

Please note, today is my last day before vacations and I'll be available in Jan after this.
