### ISSUE TITLE
The connection is not private.

### ISSUE THREAD

**Issue by lAmxCastro** [SalesforceLabs/survey-force#52]
We find the error in the certificate which has the origin: a248.e.akamai.net, which causes that the filling of the survey by our clients is not carried out.

Therefore, we ask for your support to know if there is any way to remove or remove the certificate from the package.
![Error_Survey](https://user-images.githubusercontent.com/60371183/73225465-5ea0fb00-4132-11ea-9ece-96a18640753b.JPG)

**Comment by jrattanpal** [comment]
There are no certificates in this app. This seems most likely an issue with sites in general. If this persists then please log a case with Salesforce support.
