### ISSUE TITLE
Unable to submit survey

### ISSUE THREAD

**Issue by jarrods123** [SalesforceLabs/survey-force#54]
Object settings are set as follows for the site guest profile;

-- Surveys: Read, View All (Because Guest user need to see an existing record)
-- Survey Questions: Read, View All, Modify All (Because Guest user need to see and modify an existing record)
-- Survey Question Responses: Read, Create (Because Guest user need to create a new record but does NOT need access to existing record)
-- Surveys Taken: Read, View All, Modify All (Because Guest user need to see and modify an existing record))

Url: http://devmaster-criterion.cs112.force.com/feedback/TakeSurvey?id=a3k0T0000004CdvQAE&cId=none&caId=none

OWD: External Public Read/Write for Survey object. 

Able to successfully reach the link, however clicking submit button does not redirect to anywhere, and does not log any response.

**Comment by jrattanpal** [comment]
Please capture debug logs and check (and share). It seems there is some other error which is causing issue; most likely permission issue on another object maybe.

**Comment by jarrods123** [comment]
Hi jrattanpal, thanks for the quick reply, here are a few debug logs. 
[apex-07L0T000000TIYYUA4.log](https://github.com/SalesforceLabs/survey-force/files/4183157/apex-07L0T000000TIYYUA4.log)

[apex-07L0T000000TIYTUA4.log](https://github.com/SalesforceLabs/survey-force/files/4183158/apex-07L0T000000TIYTUA4.log)

[apex-07L0T000000TIYEUA4.log](https://github.com/SalesforceLabs/survey-force/files/4183159/apex-07L0T000000TIYEUA4.log)

**Comment by jarrods123** [comment]
Here are some more at a finer debug level. 
[apex-07L0T000000TIZlUAO.log](https://github.com/SalesforceLabs/survey-force/files/4183236/apex-07L0T000000TIZlUAO.log)

[apex-07L0T000000TIZqUAO.log](https://github.com/SalesforceLabs/survey-force/files/4183237/apex-07L0T000000TIZqUAO.log)

[apex-07L0T000000TIZvUAO.log](https://github.com/SalesforceLabs/survey-force/files/4183239/apex-07L0T000000TIZvUAO.log)

[apex-07L0T000000TIa0UAG.log](https://github.com/SalesforceLabs/survey-force/files/4183240/apex-07L0T000000TIa0UAG.log)

**Comment by jarrods123** [comment]
Hi jrattanpal, I was able to resolve the issue, SurveyTaker__c was requiring create permissions on all it's fields being used instead of just view.

**Comment by jrattanpal** [comment]
I am glad it was resolved. Thanks for the update!

I'll close this ticket for now
