### ISSUE TITLE
Apex Authorization Error

### ISSUE THREAD

**Issue by jmartier** [SalesforceLabs/survey-force#55]
Despite the site settings being set to public and the site's guest user being given access to all of the survey objects and actions, guest users cannot take the survey. Viewing in administrator mode produces a blank error box. Salesforce support and a comment from the developer suggested that this was an Apex error of some sort. Attached is the debug log that was created from setting a trace flag on the Surveyforce Site Guest User. Nothing particularly stood out to me as being the specific error it is producing, but perhaps someone with more Apex experience can make something out of it.
[apex-07L1Q00000jRPxWUAW.log](https://github.com/SalesforceLabs/survey-force/files/4183537/apex-07L1Q00000jRPxWUAW.log)

**Comment by jrattanpal** [comment]
It maybe permission issue somewhere that it doesn't show data. I see following in the log. You can look at those and see what maybe happening and why does it not return data at that point.


16:18:37.0 (88584112)|HEAP_ALLOCATE|[291]|Bytes:5
16:18:37.0 (88595778)|METHOD_EXIT|[78]|01p1Q00000JYBcD|SFDCAccessController.checkAuthorizedToView(Schema.SObjectType, List<Schema.SObjectField>, Boolean)
16:18:37.0 (88609600)|METHOD_EXIT|[131]|01p1Q00000JYBcD|SFDCAccessController.assertAuthorizedToView(Schema.SObjectType, List<Schema.SObjectField>)
16:18:37.0 (88615112)|STATEMENT_EXECUTE|[133]
16:18:37.0 (88637695)|HEAP_ALLOCATE|[133]|Bytes:4
16:18:37.0 (88997035)|SOQL_EXECUTE_BEGIN|[133]|Aggregations:0|SELECT Name, Id, URL__c, Thank_You_Text__c, thankYouText__c, thankYouLink__c, Survey_Header__c, Survey_Container_CSS__c FROM Survey__c WHERE Id = :tmpVar1
16:18:37.0 (94466338)|SOQL_EXECUTE_END|[133]|Rows:0
16:18:37.0 (94511500)|HEAP_ALLOCATE|[133]|Bytes:4
16:18:37.0 (94528531)|HEAP_ALLOCATE|[133]|Bytes:0
16:18:37.0 (94586096)|HEAP_ALLOCATE|[133]|Bytes:4
16:18:37.0 (94635760)|HEAP_ALLOCATE|[133]|Bytes:46
16:18:37.0 (94695572)|VARIABLE_SCOPE_BEGIN|[145]|e|Exception|true|false
16:18:37.0 (94874474)|VARIABLE_ASSIGNMENT|[145]|e|"common.apex.runtime.impl.ExecutionException: List has no rows for assignment to SObject"|0x6094baa5
16:18:37.0 (94884340)|STATEMENT_EXECUTE|[145]
16:18:37.0 (94887309)|STATEMENT_EXECUTE|[145]
16:18:37.0 (94960181)|VF_PAGE_MESSAGE|Some error occured while saving response
16:18:37.0 (94984813)|METHOD_EXIT|[86]|01p1Q00000JYBcQ|ViewSurveyController.setSurveyNameAndThankYou(String)
16:18:37.0 (94991636)|STATEMENT_EXECUTE|[87]
