### ISSUE TITLE
Adding a new lookup field to Surveys taken

### ISSUE THREAD

**Issue by jarrods123** [SalesforceLabs/survey-force#56]
Hi, 

I'm wondering what the process would be to add a new lookup field to be auto-populated like contact and case in the url via id, this would be for a custom object.

**Comment by jrattanpal** [comment]
Logic for adding Contact/Case ID fields is in https://github.com/SalesforceLabs/survey-force/blob/master/src/classes/ViewSurveyController.cls

IF you search for "ContactId", you will see logic there like

- Line #49 
- Line#54
- Line#362
