### ISSUE TITLE
How to upgrade to latest version ?

### ISSUE THREAD

**Issue by ChrisITBRM** [SalesforceLabs/survey-force#61]
Hello,
With new Spring 20 security settings, I would like to upgrade Survey force package.
But there is an error "Can not upgrade this package"
Any way to upgrade without uninstalling and losing all data ?
Thank you for your help.

**Comment by jrattanpal** [comment]
As this is un-managed package, you cannot upgrade it via regular process.
You have couple of ways to "upgrade"

   - Uninstall existing package and install new version
      - However, you will loose any configurations done on your surveys so
      this is not advised
   - Pull code from this GitHub repo in your sandbox
      - Do regression testing to make sure everything works and then move
      this to production

2nd option is safest (if not easiest) to ensure you do not loose any
configurations.

**Comment by ChrisITBRM** [comment]
Thank you very much.
I upgrade the package and it works with new security settings.
