### ISSUE TITLE
Argument cannot be null.

### ISSUE THREAD

**Issue by cbhutia** [SalesforceLabs/survey-force#62]
Hi! I'm new to all this and I was trying to set up the app, however, I'm getting this error message when I try to preview TakeSurvey VF page.

"An unexpected error has occurred. Your development organization has been notified."

Here's the APEX code:

<apex:page standardcontroller="Survey__c" extensions="ViewSurveyController" cache="false" sidebar="false" showheader="false" lightningStylesheets="true">
    <apex:includeScript value="{! $Resource.SurveyForce_jquery}"/>
    
    <apex:includeScript value="{! $Resource.SurveyForce + '/surveyforce.js'}"/>
    <apex:stylesheet value="{! $Resource.SurveyForce + '/surveyforce.css'}"/>
    <apex:stylesheet value="{! $Resource.SurveyForce + '/surveyforce_pagemessage_override.css'}"/>
    <apex:stylesheet value="{! $Resource.SurveyForce_SLDS + '/assets/styles/salesforce-lightning-design-system-vf.min.css'}"/>

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />

    <script id="test2">
        $(document).ready(function(){
            //Convert any elements with "convertToLDS" style to SLDS styles
            //Used in certain places where it's not easy to use SLDS for those elements like "apex:selectCheckboxes"
            //convertCheckBoxToLDS();

            //Commented above function in lieu of lightningStylesheets="true"
        });
    </script>
    
    <style>
        <apex:outputText value="{!HTMLENCODE(surveyContainerCss)}" escape="false"/>
    </style>

    <div id="survey_container" class="surveyforce">
        <apex:form id="theForm"   >

            <apex:outputPanel id="seeSurvey" rendered="{! If((Survey__c.Hide_Survey_Name__c == false || Survey__c.Survey_Header__c != ''), True, False )}" >
                <div class="slds-box slds-theme--shade">
                    <div class="slds-text-heading--large"><apex:outputText value="{!Survey__c.Survey_Header__c}" escape="false" /> </div>
                    <apex:outputPanel rendered="{!Survey__c.Hide_Survey_Name__c == false}">
                        <div class="slds-text-heading--medium">{!Survey__c.Name}</div>
                    </apex:outputPanel>
                </div>
            </apex:outputPanel>

            <script>
                $(document).ready(function(){
                    overridePageMessages();
                });
            </script>

            <apex:pageMessages />
            
            <c:uiMessage severity="success" message="{!surveyThankYouText}" renderMe="{!thankYouRendered == true}" />

            <apex:outputPanel rendered="{!thankYouRendered == false}">
                <div class="slds-form--stacked">
                    <apex:repeat value="{!allQuestions}" var="qPreview" id="aQPreview">
                        <div class="slds-box slds-theme--default">
                            <div class="slds-form-element">
                                <label class="slds-form-element__label">

                                    <apex:outputText escape="true" value="{!qPreview.orderNumber + ': ' + qPreview.question}"/>

                                        <apex:outputText rendered="{! qPreview.required}" value="({!$Label.LABS_SF_Required})"  />
                                </label>
                            </div>
                            <apex:outputPanel rendered="{!qPreview.renderSelectRadio}">
                                <apex:selectRadio styleClass="convertToLDS" layout="pageDirection" rendered="{!qPreview.renderSelectRadio}" value="{!qPreview.selectedOption}" >
                                    <apex:selectOptions value="{!qPreview.singleOptions}"/>
                                </apex:selectRadio>
                            </apex:outputPanel>

                            <apex:outputPanel rendered="{!qPreview.renderSelectCheckboxes}">
                                <apex:selectCheckboxes styleClass="convertToLDS" layout="pageDirection" rendered="{!qPreview.renderSelectCheckboxes}" value="{!qPreview.selectedOptions}" >
                                    <apex:selectOptions value="{!qPreview.multiOptions}"/>
                                </apex:selectCheckboxes>
                            </apex:outputPanel>
                            <apex:outputPanel rendered="{!qPreview.renderFreeText}">
                                <div class="slds-form-element">
                                    <div class="slds-form-element__control" >
                                        <apex:inputTextArea styleClass="slds-textarea" cols="" rows="{!qPreview.noOfRowsForTextArea}" rendered="{!qPreview.renderFreeText}" value="{!qPreview.choices}"/>
                                    </div>
                                </div>
                            </apex:outputPanel>
                            <apex:outputPanel rendered="{!qPreview.renderSelectRow}">
                                <apex:selectRadio styleClass="convertToLDS" rendered="{!qPreview.renderSelectRow}" value="{!qPreview.selectedOption}">
                                    <apex:selectOptions value="{!qPreview.rowOptions}"/>
                                </apex:selectRadio>
                            </apex:outputPanel>
                        </div>
                    </apex:repeat>
                </div>
            </apex:outputPanel>
            <apex:outputPanel rendered="{!thankYouRendered == false}">
                <div class="slds-box slds-theme--default">
                    <apex:outputPanel rendered="{!isInternal}" >
                            <span class="slds-text-body--regular">{!$Label.LABS_SF_Answer_as}:</span>
                            <apex:selectRadio value="{!anonymousAnswer}">
                                <apex:selectOptions value="{!anonymousOrUser}" />
                            </apex:selectRadio>
                            <br />
                    </apex:outputPanel>
                    <apex:commandButton styleClass="slds-button slds-button--brand" action="{!submitResults}" value="{!$Label.LABS_SF_SubmitSurvey}" rerender="theForm,seeSurvey,test" />
                </div>
            </apex:outputPanel>
        </apex:form>
    </div>
</apex:page>

Thanks a lot!

**Comment by cbhutia** [comment]
Any help is appreciated!

**Comment by jrattanpal** [comment]
Hi,

That's VF page not Apex code. And even code will not. YOu will need to
collect debug logs and share to see where that error is coming from.

Also, make sure you have the latest code for this app as many errors have
been fixed in latest code.

**Comment by cbhutia** [comment]
Sorry I have almost no idea about coding. I thought that was it.
Here's what I received in my email;

Apex script unhandled exception by user/organization: 0050J000009BRjW/00D20000000mMnY

Visualforce Page: /apex/TakeSurvey



caused by: System.NullPointerException: Argument cannot be null.

Class.ViewSurveyController.<init>: line 57, column 1

On the other hand, I installed the app through the appexchange about a few hours ago. I think it's the latest version(?)

**Comment by jrattanpal** [comment]
Code you mentioned is
https://github.com/SalesforceLabs/survey-force/blob/master/force-app/main/default/classes/ViewSurveyController.cls
Line#57 is *surveyId = String.escapeSingleQuotes(surveyId); *(That is if
you have the latest code, check code in your own org to see what line is
that)

Make sure that you are using proper URL and "id=" in the URL is NOT empty.
(something like /TakeSurvey?id=xxxxxxx)
