### ISSUE TITLE
I can't install Survey Force

### ISSUE THREAD

**Issue by YMC-Fujimoto** [SalesforceLabs/survey-force#63]
I've tried installing Survey Force, but can't install it.
When I try to install, I get the following error message.

The name "Lightning" is already used in component type custom apps. Change the name of an existing component.

But I don't remember developing such an application. If it is a standard application, changing the name according to the error message is risky.

How can I install SurveyForce?

**Comment by jrattanpal** [comment]
Hi,

Have you tried installing it in a different org? (Maybe a trial org for testing or a sandbox). 

Does it work there? 

I haven't come across this error before

**Comment by YMC-Fujimoto** [comment]
Hi

I was able to install on Sandbox.
Eventually, the "Lightning" application was renamed.
I don't know why there was an application called "Lightning".

Thank you.
