### ISSUE TITLE
thank you page does not show

### ISSUE THREAD

**Issue by januconn92** [SalesforceLabs/survey-force#64]
Hi, we are trying to send a link in an email for a survey to be completed.  Each time we will have a contact ID to populate the URL but NO case ID, when i try to set the case id to none and use a different contact ID, it does NOT generate the thank you page, but instead refreshes to the same survey page.  Any help is REALLY appreciated.

**Comment by jrattanpal** [comment]
Can you capture debug logs and post those?

Also, are you using the latest version (from AppExchange) or latest code
(From this repo)? I made many fixes so it could be related to those.
