### ISSUE TITLE
visualforce.com refused to connect.

### ISSUE THREAD

**Issue by micqualtrailhead** [SalesforceLabs/survey-force#67]
Have just installed in a sandbox 

when clicking on the survey tab and a survey name I get this error 
catholiccare--foundation--c.visualforce.com refused to connect.

**Comment by jrattanpal** [comment]
Hi,

That is not related to Survey Force. Maybe there was an error?  Can you try
again?

**Comment by andyreising** [comment]
We had this same issue after first installing Survey Force. We were able to resolve it in **Session Settings** 

1. Add force.com to Trusted Domains, `https://*.force.com`
2. Check both of the checkboxes for 'Enable clickjack protection for customer Visualforce pages with standard headers' and 'Enable clickjack protection for customer Visualforce pages with headers disabled'
