### ISSUE TITLE
unable to insert Survey Question Responses

### ISSUE THREAD

**Issue by roycejudd** [SalesforceLabs/survey-force#75]
It will no longer insert Survey Question Responses.  I see the error
Error:
Some error occured while saving response
it will create the Surveys Taken object on the case but does not have any associated responses.  I have attached the debug log.

[apex-07L2S000049vwuiUAA.log](https://github.com/SalesforceLabs/survey-force/files/4974436/apex-07L2S000049vwuiUAA.log)

**Comment by jrattanpal** [comment]
Following is what I see in the log file. You maybe missing permissions on one of the objects. Please check instructions on this repo to see which objects need which permissions; especially for Site Guest user (https://github.com/SalesforceLabs/survey-force/blob/master/readme.md)


22:13:26.0 (165903377)|EXCEPTION_THROWN|[335]|System.DmlException: Insert failed. First exception on row 0; first error: INSUFFICIENT_ACCESS_ON_CROSS_REFERENCE_ENTITY, insufficient access rights on cross-reference id: []
22:13:26.0 (166480185)|HEAP_ALLOCATE|[335]|Bytes:157
22:13:26.0 (166547752)|VARIABLE_SCOPE_BEGIN|[338]|e|Exception|true|false
22:13:26.0 (166839767)|VARIABLE_ASSIGNMENT|[338]|e|"common.apex.runtime.impl.DmlExecutionException: Insert failed. First exception on row 0; first error: INSUFFICIENT_ACCESS_ON_CROSS_REFERENCE_ENTITY, insufficient access rights on cross-reference id: []"|0xd5eb208
22:13:26.0 (166855672)|STATEMENT_EXECUTE|[338]
22:13:26.0 (167070932)|VARIABLE_ASSIGNMENT|[EXTERNAL]|this|{"allQuestions":"0x3d059406","allQuestionsSize":3,"anonymousAnswer":"Anonymous","anonymousOrUser":"0x8befcc0","baseURL":"https://vulcan7.secu (12 more) ...","caseId":"5002S00001BZvfAQAT","contactId":"003E000000JvktPIAR","isInternal":false,"newOrder":"0x299ffb83","qChoices":"","qQuestion":"","renderSurveyPreview":"false","surveyContainerCss":"#survey_container{ma (110 more) ...","surveyHeader":"<div style=\"text-ali (224 more) ...","surveyId":"a1U44000007vHinEAE","surveyName":"Post Call Survey","surveyTakerId":"a1S2S000004DVlDUAW","surveyThankYouText":"Your survey has been (44 more) ...","templateURL":"Undefinedid=a1U44000 (10 more) ...","thankYouRendered":false,"userId":"00544000008pqI7AAI","userName":"SurveyForce Site Gue (7 more) ..."}|0x7ab9a76c
22:13:26.0 (167103779)|STATEMENT_EXECUTE|[341]
22:13:26.0 (167106953)|STATEMENT_EXECUTE|[342]
22:13:26.0 (167114700)|HEAP_ALLOCATE|[342]|Bytes:11
22:13:26.0 (167162385)|HEAP_ALLOCATE|[342]|Bytes:153
22:13:26.0 (167189981)|HEAP_ALLOCATE|[342]|Bytes:164
22:13:26.0 (167207663)|USER_DEBUG|[342]|DEBUG|Exception: Insert failed. First exception on row 0; first error: INSUFFICIENT_ACCESS_ON_CROSS_REFERENCE_ENTITY, insufficient access rights on cross-reference id: []
22:13:26.0 (167219156)|STATEMENT_EXECUTE|[343]
22:13:26.0 (167231789)|HEAP_ALLOCATE|[343]|Bytes:40
22:13:26.0 (167515689)|VF_PAGE_MESSAGE|Some error occured while saving response
22:13:26.0 (167536847)|SYSTEM_MODE_EXIT|false
22:13:26.193 (193923097)|SYSTEM_MODE_ENTER|true

**Comment by roycejudd** [comment]
Thank you for pointing me in the right direction.  I found out Secure guest user record access has been turned on. 

"Secure guest user record access": Enabling this will stop Guest user access to Salesforce org data. Enabling this may result in Guest user not having access to Survey Force records. More details are at: https://help.salesforce.com/articleView?id=networks_secure_guest_user_sharing.htm&type=5. Be careful when enabling this feature.

**Comment by jrattanpal** [comment]
Please note that this feature may be auto turned on in next few releases, without an option to disable it.

You should pull latest code from this repo which fixed that issue even with that feature on. You will need to manually pull all latest code from this repo and change your own code. If you have done any customizations then be careful as it may overwrite those.
