### ISSUE TITLE
Survey Force App error when opening the Survey

### ISSUE THREAD

**Issue by MeytalLo** [SalesforceLabs/survey-force#81]
Hi,
we encounter an issue with our Survey in the last month (maybe due to an update?)
when clicking the Survey Link from the email we are getting the following error:

"Authorization Required

You must first log in or register before accessing this page.
If you have forgotten your password, click Forgot Password to reset it"

when going to Site it shows that our Site is under construction.

please advise
thanks in advance.

**Comment by jrattanpal** [comment]
It seems like you maybe missing a step. Please make sure to follow all configuration steps (Adding VF page to Force.com site, assigning proper permissions to site guest user, creating sharing rules etc) as mentioned at https://github.com/SalesforceLabs/survey-force

**Comment by MeytalLo** [comment]
hi,
do I need to uninstall and installed the App?

**Comment by jrattanpal** [comment]
No, you don't need to install the app but you do need to pull new source code to your org. 

You will need to have someone who can help you moving code from THIS repo to your org

**Comment by benboren** [comment]
Hi Jaswinder,
I'm working in MeytalLo organization.

I've tried many things:
- Create and change sharing rules.
- Change class from "with sharing" to "without sharing",
- Check updates in package on github - got a lot of errors.

Can you please advise me how to solve the problem?

thank you very much in advance for your help,

**Comment by jrattanpal** [comment]
Hi,

Can you confirm that you have followed ALL steps mentioned at https://github.com/SalesforceLabs/survey-force?

If that doesn't work then please collect debug logs for guest users to see what maybe causing this issue. https://releasenotes.docs.salesforce.com/en-us/winter17/release-notes/rn_forcecom_debugging_guest_user.htm

You can share the debug logs here and I can try and look through those.
