### ISSUE TITLE
Creating Force.com site in Post Install Guide - Public Facing Surveys

### ISSUE THREAD

**Issue by ISingThis** [SalesforceLabs/survey-force#83]
Please be aware that the first point under Surveys in Force.com sites (Create a Force.com Site.  Details, including "Creating A Force.com Site") takes you to a landing page which advises that the content on the page has retired.

**Comment by jrattanpal** [comment]
Thanks for reporting this. I have updated readme file to correct those links.

Please check and let me know if you have any issues.

Thanks
