### ISSUE TITLE
Cannot set font size for questions

### ISSUE THREAD

**Issue by dardenadams** [SalesforceLabs/survey-force#84]
Using the CSS input, I'm not able to set font size for survey questions. Applying to #survey_container works for radio button text, but didn't work for the questions themselves. I tracked down the class for the question text in your source code (.slds-form-element__label), but still no joy. I can apply font style or font weight here and it works; just not font size.

The default is way too small, imo, so hoping someone can point me in the right direction.

**Comment by jrattanpal** [comment]
I tried following CSS and it worked.

#survey_container .slds-form-element__label{font-size: 1rem;}

Please make sure you are using correct selectors and in correct order.

**Comment by dardenadams** [comment]
Awesome, that worked - Thanks!
