### ISSUE TITLE
Prevent Submit button on TakeSurvey to be clicked twice

### ISSUE THREAD

**Issue by jrattanpal** [SalesforceLabs/survey-force#88]
Reported at https://appexchange.salesforce.com/appxListingDetail?listingId=a0N30000003I2gDEAS&revId=a6H3u000000TW8oEAG

REPLACE Line#98 in https://github.com/SalesforceLabs/survey-force/blob/master/force-app/main/default/pages/TakeSurvey.page

WITH

<apex:actionStatus id="submitStatus">
                        <apex:facet name="stop">
                            <apex:commandButton status="submitStatus" styleClass="slds-button slds-button--brand" action="{!submitResults}" value="{!$Label.LABS_SF_SubmitSurvey}" rerender="theForm,seeSurvey,test" />
                        </apex:facet>
                        <apex:facet name="start">
                            <apex:commandButton value="Saving..." disabled="true" status="submitStatus"/>
                        </apex:facet>
                    </apex:actionStatus>

**Comment by dschach** [comment]
I don't see anything different in the proposed change at line 98

**Comment by jrattanpal** [comment]
Change was submitted to GitHub AND new version (2.54) published on AppExchange

https://github.com/SalesforceLabs/survey-force/commit/04778b68c34bd99e16c060cc4829ea95ffa7e786
