### ISSUE TITLE
Issue with reinstall

### ISSUE THREAD

**Issue by Wadter** [SalesforceLabs/survey-force#89]
I uninstalled my current version from the sandbox and when I tried to reinstall I get an error

The name "Survey Force Lightning" is already used on component type: Custom App. Please rename existing component.

I saw this on trailblazers, but wanted to ask if anyone has any idea?

**Comment by jrattanpal** [comment]
It seems like you didn't delete existing components when you un-installed the package. Hence the warning because you may already have an app called "Survey Force Lightning" (because it wasn't deleted) and SurveyForce package is trying to install a component with same name

**Comment by Wadter** [comment]
@jrattanpal Thanks for the quick reply.  We thought we had it all.  I can see it when I go under the app menu, which only allows me to reorder it and doesn't seem to exist anywhere else.    I am going to give SFDC a few hours to see if it's just still processing and if nothing changes I am going to refresh and try again.

**Comment by jrattanpal** [comment]
Sounds good. Let me know how it goes. If all good then update and close the issue.

**Comment by Wadter** [comment]
@jrattanpal  - So I was able to install in our sandbox, but when I try to import the changeset, I get this error.  Any ideas?

Dependent class is invalid and needs recompilation: Class SurveyAnd Question Controller : External string does not exist: LABS_SF_Default_Option_Label

**Comment by jrattanpal** [comment]
LABS_SF_Default_Option_Label are custom labels. It should be there. 

But if it's not in production then make sure you have added those to your change set

**Comment by Wadter** [comment]
<img width="1035" alt="Screen Shot 2020-11-11 at 2 51 13 PM" src="https://user-images.githubusercontent.com/74270040/98857676-5d289100-242d-11eb-9585-a9a900f9a519.png">
 @jrattanpal  - So we got that to work, but these test classes are failing when we move to production.

**Comment by jrattanpal** [comment]
I am not sure as those tests should pass unless some manual changes have been made. You will need to capture debug logs and figure out what maybe happening there.

Tests are running because you are trying to promote changes from sandbox to production. 

Sorry, it needs to be debugged slowly to figure out why those are failing for you. So far, those have worked for others without issues.

**Comment by Wadter** [comment]
@jrattanpal 
Thanks so much for your help, it is working now. I appreciate the fast replies.
