### ISSUE TITLE
Authorization Required

### ISSUE THREAD

**Issue by GlobalEagleSurveyForce** [SalesforceLabs/survey-force#92]
We checked everything. Still Customers are getting this message.

**Comment by jrattanpal** [comment]
Can you attach debug logs? that will help figure out what maybe the issue

It's definitely a missed setting somewhere (a sharing rule, adding VF page to site etc)

**Comment by jrattanpal** [comment]
You can capture debug logs for a site guest user  with following mechanism. After setting up debug logs, you can visite that Force.com site page yourself and it should capture debug logs that you can attach here.

- https://releasenotes.docs.salesforce.com/en-us/winter17/release-notes/rn_forcecom_debugging_guest_user.htm
- https://help.salesforce.com/articleView?id=code_add_users_debug_log.htm&type=5

**Comment by GlobalEagleSurveyForce** [comment]
Good Day,
Here are the logs..

[cid:image001.png@01D6E43F.5AB82B20]

Please let us know.


Best Regards,
Shilpa Poduri

**Comment by jrattanpal** [comment]
It seems like Site guest user doesn't have access to Survey record. When you query for it, it doesn't return anything and it fails with "List has no rows.....".


2 things that can cause this, that are mentioned in https://github.com/SalesforceLabs/survey-force, are:
- Points 2, 3, 4 as mentioned under "Surveys in Force.com sites" heading  (CRUD/FLS permission for Survey object)
- Point 3 under "Extra Notes" (Sharing rule for Survey object for Guest user)

**Comment by GlobalEagleSurveyForce** [comment]
Good Day,
Completed . Thank you. Please close our ticket.
[cid:image002.jpg@01D6E4DD.386C5F20]

Best Regards,
Shilpa Poduri

**Comment by jrattanpal** [comment]
Thanks for letting me know. I am glad it's working for you now.

**Comment by GlobalEagleSurveyForce** [comment]
Good Day,
           Can you please reopen-our ticket,
[cid:image001.png@01D6EB60.FA37B170]

Even though our customers can access a survey, they are not able to Submit it.
I checked on case object and Guset user has Read/write access.

[cid:image002.jpg@01D6EB60.FA4D8360]

Please advice.

Best Regards,
Shilpa Poduri
From: Shilpa Chekuri
Sent: Thursday, January 07, 2021 10:10 AM
To: SalesforceLabs/survey-force <reply@reply.github.com>; SalesforceLabs/survey-force <survey-force@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [SalesforceLabs/survey-force] Authorization Required (#92)



Good Day,
Completed . Thank you. Please close our ticket.
[cid:image004.jpg@01D6EB60.FA37B170]

Best Regards,
Shilpa Poduri

**Comment by jrattanpal** [comment]
What version of package do you have? Can you share the logs again?

This is because of new security changes on the site guest user. This was fixed in latest version.

AMong other changes, following changes fixed the submit issue.
- https://github.com/SalesforceLabs/survey-force/blob/master/force-app/main/default/classes/ViewSurveyController.cls (line 402)
- https://github.com/SalesforceLabs/survey-force/blob/master/force-app/main/default/classes/ViewSurveyControllerWithoutSharing.cls (new class)

**Comment by jrattanpal** [comment]
Let me know if you still need help

**Comment by shanmuka824** [comment]
Hi jrattanpal,

I am getting the below error message in my sandbox,

**Authorization Required

You must first log in or register before accessing this page.
If you have forgotten your password, click Forgot Password to reset it.**

**Below are my debug logs:**

User | Surveys Site Guest User | Date | 1/21/2021 12:21:56 PM PST
-- | -- | -- | --
Status | Success | Application | Browser
Request Type | Application | Operation | /apex/Unauthorized
Duration (ms) | 54 | Log Size (bytes) | 5,287
Log | 17.0 APEX_CODE,FINEST;APEX_PROFILING,FINEST;CALLOUT,FINEST;DB,FINEST;NBA,INFO;SYSTEM,FINE;VALIDATION,INFO;VISUALFORCE,FINER;WAVE,INFO;WORKFLOW,FINER 20:21:56.0 (109948)\|USER_INFO\|[EXTERNAL]\|00560000001LAdZ\|surveys@demand.force.com.dfull2\|Greenwich Mean Time\|GMTZ 20:21:56.0 (154465)\|EXECUTION_STARTED 20:21:56.0 (160782)\|CODE_UNIT_STARTED\|[EXTERNAL]\|06660000000CfdX\|VF: /apex/Unauthorized 20:21:56.0 (18110304)\|VF_EVALUATE_FORMULA_BEGIN\|06660000000CfdX\|#{AND(ISPICKVAL($User.UserType,'Guest'), $Site.LoginEnabled)} 20:21:56.0 (25573919)\|VF_EVALUATE_FORMULA_END 20:21:56.0 (25607001)\|VF_EVALUATE_FORMULA_BEGIN\|06660000000CfdX\|#{NOT(ISPICKVAL($User.UserType,'Guest'))} 20:21:56.0 (25644797)\|VF_EVALUATE_FORMULA_END 20:21:56.0 (25730140)\|VF_EVALUATE_FORMULA_BEGIN\|06660000000CfdX\|#{$Site.LoginEnabled && ISPICKVAL($User.UserType,'Guest')} 20:21:56.0 (25749523)\|VF_EVALUATE_FORMULA_END 20:21:56.0 (26793515)\|VF_EVALUATE_FORMULA_BEGIN\|06660000000CfdX\|#{$Site.Prefix}/img/sites/force_logo.gif 20:21:56.0 (26832894)\|VF_EVALUATE_FORMULA_END 20:21:56.0 (26907047)\|VF_EVALUATE_FORMULA_BEGIN\|06660000000CfdX\|#{AND(ISPICKVAL($User.UserType,'Guest'), $Site.LoginEnabled)} 20:21:56.0 (26948742)\|VF_EVALUATE_FORMULA_END 20:21:56.0 (26954971)\|VF_EVALUATE_FORMULA_BEGIN\|06660000000CfdX\|#{NOT(ISPICKVAL($User.UserType,'Guest'))} 20:21:56.0 (26971214)\|VF_EVALUATE_FORMULA_END 20:21:56.0 (27134930)\|VF_EVALUATE_FORMULA_BEGIN\|06660000000CfdX\|#{URLFOR($Resource.SiteSamples, 'img/clock.png')} 20:21:56.0 (27448667)\|VF_EVALUATE_FORMULA_END 20:21:56.0 (27486636)\|VF_EVALUATE_FORMULA_BEGIN\|06660000000CfdX\|#{URLFOR($Resource.SiteSamples, 'img/unauthorized.gif')} 20:21:56.0 (27515810)\|VF_EVALUATE_FORMULA_END 20:21:56.0 (27681837)\|VF_EVALUATE_FORMULA_BEGIN\|06660000000CfdX\|#{$Site.LoginEnabled && ISPICKVAL($User.UserType,'Guest')} 20:21:56.0 (27702382)\|VF_EVALUATE_FORMULA_END 20:21:56.0 (31669011)\|VF_EVALUATE_FORMULA_BEGIN\|06660000000CfdX\|#{URLFOR($Resource.SiteSamples, 'img/poweredby.png')} 20:21:56.0 (31746478)\|VF_EVALUATE_FORMULA_END 20:21:56.0 (32105342)\|VF_EVALUATE_FORMULA_BEGIN\|06660000000CfdX\|#{URLFOR($Resource.SiteSamples, 'img/poweredby.png')} 20:21:56.0 (32142184)\|VF_EVALUATE_FORMULA_END 20:21:56.0 (32484300)\|VF_EVALUATE_FORMULA_BEGIN\|06660000000CfdX\|#{AND(ISPICKVAL($User.UserType,'Guest'), $Site.LoginEnabled)} 20:21:56.0 (32536404)\|VF_EVALUATE_FORMULA_END 20:21:56.0 (32543386)\|VF_EVALUATE_FORMULA_BEGIN\|06660000000CfdX\|#{NOT(ISPICKVAL($User.UserType,'Guest'))} 20:21:56.0 (32560982)\|VF_EVALUATE_FORMULA_END 20:21:56.0 (32577647)\|VF_EVALUATE_FORMULA_BEGIN\|06660000000CfdX\|#{$Site.LoginEnabled && ISPICKVAL($User.UserType,'Guest')} 20:21:56.0 (32589410)\|VF_EVALUATE_FORMULA_END 20:21:56.0 (34079182)\|VF_EVALUATE_FORMULA_BEGIN\|06660000000CfdX\|#{URLFOR($Resource.SiteSamples, 'SiteStyles.css')} 20:21:56.0 (34121458)\|VF_EVALUATE_FORMULA_END 20:21:56.0 (34145785)\|VF_EVALUATE_FORMULA_BEGIN\|06660000000CfdX\|#{AND(ISPICKVAL($User.UserType,'Guest'), $Site.LoginEnabled)} 20:21:56.0 (34191661)\|VF_EVALUATE_FORMULA_END 20:21:56.0 (34197926)\|VF_EVALUATE_FORMULA_BEGIN\|06660000000CfdX\|#{NOT(ISPICKVAL($User.UserType,'Guest'))} 20:21:56.0 (34214611)\|VF_EVALUATE_FORMULA_END 20:21:56.0 (34234610)\|VF_EVALUATE_FORMULA_BEGIN\|06660000000CfdX\|#{$Site.LoginEnabled && ISPICKVAL($User.UserType,'Guest')} 20:21:56.0 (34246543)\|VF_EVALUATE_FORMULA_END 20:21:56.0 (35030629)\|VF_EVALUATE_FORMULA_BEGIN\|06660000000CfdX\|#{URLFOR($Resource.SiteSamples, 'SiteStyles.css')} 20:21:56.0 (35076701)\|VF_EVALUATE_FORMULA_END 20:21:56.0 (35106867)\|VF_EVALUATE_FORMULA_BEGIN\|06660000000CfdX\|#{AND(ISPICKVAL($User.UserType,'Guest'), $Site.LoginEnabled)} 20:21:56.0 (35157398)\|VF_EVALUATE_FORMULA_END 20:21:56.0 (35164152)\|VF_EVALUATE_FORMULA_BEGIN\|06660000000CfdX\|#{NOT(ISPICKVAL($User.UserType,'Guest'))} 20:21:56.0 (35180520)\|VF_EVALUATE_FORMULA_END 20:21:56.0 (35198849)\|VF_EVALUATE_FORMULA_BEGIN\|06660000000CfdX\|#{$Site.LoginEnabled && ISPICKVAL($User.UserType,'Guest')} 20:21:56.0 (35210295)\|VF_EVALUATE_FORMULA_END 20:21:56.36 (36703643)\|CUMULATIVE_LIMIT_USAGE 20:21:56.36 (36703643)\|LIMIT_USAGE_FOR_NS\|(default)\|   Number of SOQL queries: 0 out of 100   Number of query rows: 0 out of 50000   Number of SOSL queries: 0 out of 20   Number of DML statements: 0 out of 150   Number of Publish Immediate DML: 0 out of 150   Number of DML rows: 0 out of 10000   Maximum CPU time: 0 out of 10000   Maximum heap size: 0 out of 6000000   Number of callouts: 0 out of 100   Number of Email Invocations: 0 out of 10   Number of future calls: 0 out of 50   Number of queueable jobs added to the queue: 0 out of 50   Number of Mobile Apex push calls: 0 out of 10  20:21:56.36 (36703643)\|TOTAL_EMAIL_RECIPIENTS_QUEUED\|0 20:21:56.36 (36703643)\|CUMULATIVE_LIMIT_USAGE_END  20:21:56.0 (36749793)\|CODE_UNIT_FINISHED\|VF: /apex/Unauthorized 20:21:56.0 (36765213)\|EXECUTION_FINISHED 20:21:56.37 (37932548)\|CUMULATIVE_PROFILING_BEGIN 20:21:56.37 (37932548)\|CUMULATIVE_PROFILING\|No profiling information for SOQL operations 20:21:56.37 (37932548)\|CUMULATIVE_PROFILING\|No profiling information for SOSL operations 20:21:56.37 (37932548)\|CUMULATIVE_PROFILING\|No profiling information for DML operations 20:21:56.37 (37932548)\|CUMULATIVE_PROFILING\|No profiling information for method invocations 20:21:56.37 (37932548)\|CUMULATIVE_PROFILING_END


User | Surveys Site Guest User | Date | 1/21/2021 12:21:56 PM PST
-- | -- | -- | --
Status | Success | Application | Browser
Request Type | Application | Operation | /apex/TakeSurvey
Duration (ms) | 39 | Log Size (bytes) | 1,668
Log | 18.0 APEX_CODE,FINEST;APEX_PROFILING,FINEST;CALLOUT,FINEST;DB,FINEST;NBA,INFO;SYSTEM,FINE;VALIDATION,INFO;VISUALFORCE,FINER;WAVE,INFO;WORKFLOW,FINER 20:21:55.0 (116190)\|USER_INFO\|[EXTERNAL]\|00560000001LAdZ\|surveys@demand.force.com.dfull2\|Greenwich Mean Time\|GMTZ 20:21:55.0 (158326)\|EXECUTION_STARTED 20:21:55.0 (164281)\|CODE_UNIT_STARTED\|[EXTERNAL]\|06660000000LM9w\|VF: /apex/TakeSurvey 20:21:55.7 (7914608)\|CUMULATIVE_LIMIT_USAGE 20:21:55.7 (7914608)\|LIMIT_USAGE_FOR_NS\|(default)\|   Number of SOQL queries: 0 out of 100   Number of query rows: 0 out of 50000   Number of SOSL queries: 0 out of 20   Number of DML statements: 0 out of 150   Number of Publish Immediate DML: 0 out of 150   Number of DML rows: 0 out of 10000   Maximum CPU time: 0 out of 10000   Maximum heap size: 0 out of 6000000   Number of callouts: 0 out of 100   Number of Email Invocations: 0 out of 10   Number of future calls: 0 out of 50   Number of queueable jobs added to the queue: 0 out of 50   Number of Mobile Apex push calls: 0 out of 10  20:21:55.7 (7914608)\|TOTAL_EMAIL_RECIPIENTS_QUEUED\|0 20:21:55.7 (7914608)\|CUMULATIVE_LIMIT_USAGE_END  20:21:55.0 (7990152)\|CODE_UNIT_FINISHED\|VF: /apex/TakeSurvey 20:21:55.0 (8007613)\|EXECUTION_FINISHED 20:21:55.9 (9144366)\|CUMULATIVE_PROFILING_BEGIN 20:21:55.9 (9144366)\|CUMULATIVE_PROFILING\|No profiling information for SOQL operations 20:21:55.9 (9144366)\|CUMULATIVE_PROFILING\|No profiling information for SOSL operations 20:21:55.9 (9144366)\|CUMULATIVE_PROFILING\|No profiling information for DML operations 20:21:55.9 (9144366)\|CUMULATIVE_PROFILING\|No profiling information for method invocations 20:21:55.9 (9144366)\|CUMULATIVE_PROFILING_END

**Comment by jrattanpal** [comment]
Can you attach log file rather than copy/paste? It's very hard to read

**Comment by jrattanpal** [comment]
In addition, there should be another log file. That is what I need because error is on Apex side.

Also, please make sure to go through read me file again. MAKE SURE that you have followed ALL steps. In almost all cases, it was a missing setting that caused this issue.

https://github.com/SalesforceLabs/survey-force

**Comment by GlobalEagleSurveyForce** [comment]
Good Day,
Looks like there is a confusion here. I did not give you any reply yet.
Can you please check!
Best Regards,
Shilpa Poduri

**Comment by GlobalEagleSurveyForce** [comment]
Good Day,
            What version of package do you have?
[cid:image001.jpg@01D6F019.BE943180]
Version 2.27

Can you share the logs again?
I have log 1 and log2 attached.

Please advice.

Best Regards,
Shilpa Poduri

**Comment by shanmuka824** [comment]
Hi, In production we are in version 1.20. I don't see the package in my sandbox but we have those objects.

Below are the 2 logs.
[
[apex-07L2f000007bBo9EAE.log](https://github.com/SalesforceLabs/survey-force/files/5852679/apex-07L2f000007bBo9EAE.log)
[apex-07L2f000007bBaBEAU.log](https://github.com/SalesforceLabs/survey-force/files/5852680/apex-07L2f000007bBaBEAU.log)

Thanks

](url)

**Comment by shanmuka824** [comment]
I will try in a different sandbox and will update you.

**Comment by shanmuka824** [comment]
Hi jrattanpal,

I tried in a different sandbox and I am no longer getting the error message but when I click on Submit Survey nothing is happening. Below are the debug logs.

[apex-07L7d00000vOl2AEAS.log](https://github.com/SalesforceLabs/survey-force/files/5852836/apex-07L7d00000vOl2AEAS.log)
[apex-07L7d00000vOl25EAC.log](https://github.com/SalesforceLabs/survey-force/files/5852837/apex-07L7d00000vOl25EAC.log)
[apex-07L7d00000vOl2FEAS.log](https://github.com/SalesforceLabs/survey-force/files/5852838/apex-07L7d00000vOl2FEAS.log)

Thanks,
Shanmuka

**Comment by jrattanpal** [comment]
@shanmuka824 
You need to upgrade your code to latest version. All these issues have been fixed in latest code. Please upgrade it, go through configuration and test. If you still face the issue then I can take a look.
Upgrade instructions are at https://github.com/SalesforceLabs/survey-force

If you need to report again then please create a new issue.

@GlobalEagleSurveyForce 

It seems @shanmuka824 used your issue to post his logs hence the confusion. I have asked @shanmuka824 to log a new issue (if needed after upgrade).

For your issue, let me know if you still have it (after updating to latest code and going through ALL config options mentioned at https://github.com/SalesforceLabs/survey-force).

**Comment by GlobalEagleSurveyForce** [comment]
Good Day,
            Please find the log files attached.
Thank you for letting shanmukha know ttaht this is Global Eagles ticket.
Please advice a soution to us.

Best Regards,
Shilpa Poduri
Sr.Developer, Salesforce
[SFU_CRT_BDG_Admin_RGB - small]  [AppBuilder_logo - small]   [cid:image005.png@01D6F0C1.969D8BB0]
DL 001-954-672-4496
[cid:image003.jpg@01D6F0C1.B90F7280]
Teamwork | Excellence | Action | Commitment | Honor

From: Shilpa Chekuri
Sent: Thursday, January 21, 2021 5:21 PM
To: SalesforceLabs/survey-force <reply@reply.github.com>; SalesforceLabs/survey-force <survey-force@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [SalesforceLabs/survey-force] Authorization Required (#92)



Good Day,
            What version of package do you have?
[cid:image008.jpg@01D6F0C1.969D8BB0]
Version 2.27

Can you share the logs again?
I have log 1 and log2 attached.

Please advice.

Best Regards,
Shilpa Poduri

**Comment by jrattanpal** [comment]
@GlobalEagleSurveyForce 

I am still waiting for response on my original comment to you. (Copied below from above)



What version of package do you have? Can you share the logs again? (Please make sure to attach the log files; especially Apex execution)

This is because of new security changes on the site guest user. This was fixed in latest version. AMong other changes, following changes fixed the submit issue.

https://github.com/SalesforceLabs/survey-force/blob/master/force-app/main/default/classes/ViewSurveyController.cls (line 402)
https://github.com/SalesforceLabs/survey-force/blob/master/force-app/main/default/classes/ViewSurveyControllerWithoutSharing.cls (new class)

**Comment by GlobalEagleSurveyForce** [comment]
Good Day,
Good Day,
            What version of package do you have?
[cid:image001.jpg@01D6F0C5.4457B2F0]
Version 2.27

Can you share the logs again?
I have log 1 and log2 attached.

Please advice.

Best Regards,
Shilpa Poduri
Sr.Developer, Salesforce
[SFU_CRT_BDG_Admin_RGB - small]  [AppBuilder_logo - small]   [cid:image004.png@01D6F0C5.4457B2F0]
DL 001-954-672-4496
[cid:image007.jpg@01D6F0C5.445D0A20]
Teamwork | Excellence | Action | Commitment | Honor

**Comment by jrattanpal** [comment]
@GlobalEagleSurveyForce 

v2.27 is very old. You need to update it for new changes which fix this issue introduced by new changes to Guest user account. I have listed upgrade options at https://github.com/SalesforceLabs/survey-force

As for logs, for some reason I see copied/pasted logs. Those seem to be truncated. You can attach the files themselves that I can download. There are some tools which also let me examine those logs as long as I have complete file.

**Comment by GlobalEagleSurveyForce** [comment]
Good Day,
             We have a lot of Customizations for this App. We have also implemented this for our Orders as Order Surveys.
             Now if I have to Upgrade, I will loose all those Customizations.
             Is there any way to upgrade with out loosng customizations?
             We really have a hand full of Customizations.
Best Regards,
Shilpa Poduri

**Comment by jrattanpal** [comment]
I understand and that's the hardest part.  There have been many changes since 2.27 so it's hard for me to give you list (among fixees, we cleaned up a lot of code).

For the submit part, following 2 changes should fix that. But I cannot guarantee as there were other changes too,


https://github.com/SalesforceLabs/survey-force/blob/master/force-app/main/default/classes/ViewSurveyController.cls (line 402)
https://github.com/SalesforceLabs/survey-force/blob/master/force-app/main/default/classes/ViewSurveyControllerWithoutSharing.cls (new class)

**Comment by GlobalEagleSurveyForce** [comment]
Good Day,
What is the latest version now?
Is there a way I can keep my changes in any other SF version (dev environment etc ) and then get this into a different sandbox and then do must custom changes all again?
Can we do this together?

Best Regards,
Shilpa Poduri

**Comment by jrattanpal** [comment]
Current version is 2.54.

Yes, one of the upgrade method I mentioned is:
- Create/Refresh sandbox
- Uninstall SurveyForce (but keep track of your customizations)
- Install latest package
- Add your customizations again
- Deploy to production

While I can help with these suggestions or help figuring out the issue, I am not able to help with the entire process.

You can start on this. if you face errors then I can try my best to help and figure it out.

**Comment by wahoobie** [comment]
I wanted to leave a comment thanking you @jrattanpal and the other posters on this thread. The revisions to the steps helped us resolve this issue for the upcoming Spring'21 changes and we are now in position to continue our dependence on this app and it's code branch I started with many many years ago.  Much appreciated for the continued efforts!!!!
