### ISSUE TITLE
Facing Authorization required when trying to access survey using survey force

### ISSUE THREAD

**Issue by DineshARIA** [SalesforceLabs/survey-force#93]
It was working fine for few years now. However, I am now facing 'Authorization required' now. I have followed all the steps required for installation and have the latest Survey Force app. I have also created the sharing rule required since Salesforce tightened security. I also checked all the permissions required for guest user. However, it is not working. Can you help me with this?

Thanks,
Dinesh

**Comment by jrattanpal** [comment]
I see following error
15:50:22.0 (73693692)|FATAL_ERROR|System.QueryException: List has no rows for assignment to SObject

That means one of the following:
- Guest user doesn't have View access on Survey object
- Sharing rule is not properly setup for Guest user on survey object

Those are the only 2 things I can think of

**Comment by DineshARIA** [comment]
> I see following error
> 15:50:22.0 (73693692)|FATAL_ERROR|System.QueryException: List has no rows for assignment to SObject
> 
> That means one of the following:
> 
> * Guest user doesn't have View access on Survey object
> * Sharing rule is not properly setup for Guest user on survey object
> 
> Those are the only 2 things I can think of

**Comment by DineshARIA** [comment]
I am able to access surveys but not able to submit them. 
[apex-07L4w00005B7xieEAB (1).log](https://github.com/SalesforceLabs/survey-force/files/5831687/apex-07L4w00005B7xieEAB.1.log)
I have given access to all related 4 objects along with access to Cases, Contacts, Users. But, still I face the issue of 'INSUFFICIENT_ACCESS_ON_CROSS_REFERENCE_ENTITY, insufficient access rights on cross-reference id: []'. I have also made them 'Public Read Only' for external users. Can you please help me in fixing this. Attached is my apex log. I can also connect regarding this issue.

**Comment by DineshARIA** [comment]
Sorry, I think I posted wrong log. Here is the right one.
[apex-07L4w00005B7xkuEAB.log](https://github.com/SalesforceLabs/survey-force/files/5831774/apex-07L4w00005B7xkuEAB.log)

**Comment by jrattanpal** [comment]
You sent the debug logs for visualforce. I will need Apex part to see what's going on. Having said that, you may have an older version. Please make sure to get the latest code.

If you check https://github.com/SalesforceLabs/survey-force/blob/master/force-app/main/default/classes/ViewSurveyController.cls, Your code on line# 402 should match

**Comment by DineshARIA** [comment]
I am able to fix the issue by updating the latest code.

Thanks,
Dinesh
