### ISSUE TITLE
invisible Link in Thank You Text (Survey Force)

### ISSUE THREAD

**Issue by DrLeee** [SalesforceLabs/survey-force#95]
Hi,
We created a survey, but when we test it, the link in the thank you text is not visible. Any Ideas?
Thanks!

**Comment by jrattanpal** [comment]
What is it that you put in there? I'll have to use that and test.

Also, do you have a survey link that I can try and see?

It's possible that it's happening because we strip HTML characters on that text (as part of security review). If that is the case, I'll have to see what is possible

**Comment by jrattanpal** [comment]
I will close this issue for now. If this issue persists then you can reopen this with some logs
