### ISSUE TITLE
Authorization Required

### ISSUE THREAD

**Issue by megkitt** [SalesforceLabs/survey-force#96]
None of our surveys are accessible - all are throwing error "Authorization Required" since the most recent Salesforce release approximately two weeks ago. In the release, the Sharing Setting for Secure guest user record access was reenabled, which is preventing access to our surveys. How can we allow users to access our surveys with this setting enabled? We've tried creating sharing rules for both the Survey Taken and Survey objects, which did not solve the issue.

**Comment by jrattanpal** [comment]
I tested it right now and it's all working. Make sure to follow ALL instructions mentioned at https://github.com/SalesforceLabs/survey-force; especially

- CRUD/FLS settings
- Sharing Rule
- Adding TakeSurvey to Sites

If you still get this error then please capture Apex log (for the Apex class) and add it here so I can check what maybe possible issue

**Comment by alvogt** [comment]
https://github.com/SalesforceLabs/survey-force/blob/master/readme.md This document helped me. I made the mistake of thinking I needed all the new APEX. But, what I really needed from the new version was the fields and permissions set and labels to make it work.  However, once I  uninstalled and re installed in a Partial sandbox. I have checkbox on the surveys and the Sharing Rules, and Permission Set of survey Profile all checked and set it worked in Production.  We already had TakeSurvey as a site. It was our users that reported it was broken first.

**Comment by jrattanpal** [comment]
I will close this issue fo rnow. If this error persists then please create a new issue with Apex logs
