### ISSUE TITLE
Authorization required

### ISSUE THREAD

**Issue by shrutimagarwal** [SalesforceLabs/survey-force#98]
With the spring release by Salesforce, our surveys are just giving authorization required error. We checked the settings but couldn't figure out what's wrong. Any insights will be appreciated.

**Comment by jrattanpal** [comment]
I tested it right now and it's all working. Make sure to follow ALL instructions mentioned at https://github.com/SalesforceLabs/survey-force; especially

- CRUD/FLS settings
- Sharing Rule
- Adding TakeSurvey to Sites

If you still get this error then please capture Apex log (for the Apex class) and add it here so I can check what maybe possible issue

**Comment by jrattanpal** [comment]
I will close this issue for now. If you still face the issue then you can reopen this or create a new issue.
