### ISSUE TITLE
leave out last section that allows survey completer to chk box anonymous or chk box user name that prepared survey

### ISSUE THREAD

**Issue by garysecor** [SalesforceLabs/survey-force#99]

**Comment by garysecor** [comment]
charity wants to ask a question to survey user name and leave out the bottom part that asks them to check who they are

**Comment by garysecor** [comment]
is there a way to leave off the last section of the survey form ?

**Comment by jrattanpal** [comment]
There is currently no setting to disable it. But you can make changes to remove that. 

https://github.com/SalesforceLabs/survey-force/blob/master/force-app/main/default/classes/ViewSurveyController.cls 
Line# 102: You can change that to following
isInternal = false;

This will treat all surveys as non-internal. THat variable only controls if that section shows up or not. Of course, you should test it on sandbox before promoting to production

**Comment by garysecor** [comment]
Thanks much – will test

 

GAry

 

Gary Secor

Vice President CIO

Cloudtroupe

Direct     678-478-6776 

Gary@cloudtroupe.com <mailto:Gary@cloudtroupe.com>  

www.cloudtroupe.com <http://www.cloudtroupe.com>

**Comment by garysecor** [comment]
How do I edit the controller already installed?

 

Thanks

Gary

 

Gary Secor

Vice President CIO

Cloudtroupe

Direct     678-478-6776 

Gary@cloudtroupe.com <mailto:Gary@cloudtroupe.com>  

www.cloudtroupe.com <http://www.cloudtroupe.com>

**Comment by jrattanpal** [comment]
This is an un-managed package. Once you install it, you own the code and can make any changes as needed.

**Comment by jrattanpal** [comment]
Closing it for now. Please create a new issue if more help is needed
